// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuEXc6A6PjwVcKJ9zV5FiHGsdM2EHzd3o',
    appId: '1:15585823930:web:71dbd0f5595e299f324683',
    messagingSenderId: '15585823930',
    projectId: 'note-e4fd3',
    authDomain: 'note-e4fd3.firebaseapp.com',
    storageBucket: 'note-e4fd3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEYa_GpLZnxLjGaNQTMiO7kFI1mqj1z38',
    appId: '1:15585823930:android:764746e155420d9c324683',
    messagingSenderId: '15585823930',
    projectId: 'note-e4fd3',
    storageBucket: 'note-e4fd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAJoJYrGID0vZATjcyGnbPOE0Bkp5KVFU',
    appId: '1:15585823930:ios:5e9d9f3bae38601a324683',
    messagingSenderId: '15585823930',
    projectId: 'note-e4fd3',
    storageBucket: 'note-e4fd3.appspot.com',
    iosClientId: '15585823930-u46hqlmijo7qsm2vpidpe8pkosgf9mlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAJoJYrGID0vZATjcyGnbPOE0Bkp5KVFU',
    appId: '1:15585823930:ios:5e9d9f3bae38601a324683',
    messagingSenderId: '15585823930',
    projectId: 'note-e4fd3',
    storageBucket: 'note-e4fd3.appspot.com',
    iosClientId: '15585823930-u46hqlmijo7qsm2vpidpe8pkosgf9mlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
